name: Dependency Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Scan dependencies
        run: |
          pip-audit -r requirements.txt || true
          # Using || true to prevent workflow failure, but still report vulnerabilities
          # Remove || true if you want the workflow to fail when vulnerabilities are found

      - name: Generate vulnerability report
        run: |
          pip-audit -r requirements.txt -f json > vulnerability-report.json || true
          echo "Vulnerability report generated at vulnerability-report.json"

      - name: Upload vulnerability report
        uses: actions/upload-artifact@v3
        with:
          name: vulnerability-report
          path: vulnerability-report.json
