name: Python Tests

on:
  push:
    branches: [ main, setup-repository-structure ]
  pull_request:
    branches: [ main, setup-repository-structure ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov

    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./coverage.xml
        retention-days: 5

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
